# Generated by Django 4.2.23 on 2025-07-02 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('masked_number', models.CharField(max_length=19)),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('BLOCKED', 'Заблокирована'), ('EXPIRED', 'Истек срок')], default='ACTIVE', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
        ),
    ]
